# Generated by Django 4.0.4 on 2022-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(db_column='Name', max_length=35)),
                ('email', models.CharField(db_column='Email', max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=100)),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
