# Generated by Django 4.0.4 on 2022-05-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='length',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
