# Generated by Django 4.0.4 on 2022-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_course_length_course_description_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
