# Generated by Django 4.0.4 on 2022-05-23 15:08

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('days', models.CharField(max_length=30, null=True)),
                ('trainer', models.CharField(max_length=30, null=True)),
                ('ph_no',models.CharField(blank=True, help_text='Contact Phone Number', max_length=31)),
                ('thumbnail', models.ImageField(null=True, upload_to='files/thumbnail')),
            ],
        ),
    ]
