# Generated by Django 4.0.4 on 2022-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='ph_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
