# Generated by Django 4.0.4 on 2022-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_schedule_ph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='mail_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ph_no',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
