# Generated by Django 4.0.4 on 2022-05-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_userschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userschedule',
            old_name='course',
            new_name='name',
        ),
    ]
