# Generated by Django 4.1.3 on 2022-12-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
