# Generated by Django 4.2.1 on 2023-06-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='thumbnail',
        ),
    ]
