# Generated by Django 4.2.1 on 2023-06-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_course_thumbnail_remove_schedule_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='files/thumbnail'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='files/thumbnail'),
        ),
    ]
